spring.application.name=Bookmanagement

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Optional (Best Practice)
spring.jpa.open-in-view=false

# Server Port
server.port=8081